In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 

In [2]:
data = pd.read_csv("/Users/raouz/Desktop/Capstone Project: Heart Attack Prediction/data/raw/heart.csv")

In [3]:
data.head()

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0   63    1   3     145   233    1        0       150     0      2.3    0   
1   37    1   2     130   250    0        1       187     0      3.5    0   
2   41    0   1     130   204    0        0       172     0      1.4    2   
3   56    1   1     120   236    0        1       178     0      0.8    2   
4   57    0   0     120   354    0        1       163     1      0.6    2   

   caa  thall  output  
0    0      1       1  
1    0      2       1  
2    0      2       1  
3    0      2       1  
4    0      2       1

In [4]:
data['thall']

0      1
1      2
2      2
3      2
4      2
      ..
298    3
299    3
300    3
301    3
302    2
Name: thall, Length: 303, dtype: int64

In [5]:
data['thall'].unique()

array([1, 2, 3, 0])

In [6]:
mode = data['thall'].mode()

In [7]:
mean = data['thall'].mean()

In [8]:
median =data['thall'].median()

In [9]:
data3 = data

In [10]:
data3['thall'].unique()

array([1, 2, 3, 0])

In [13]:
data3['thall'] = data3['thall'].replace(2,mode)

In [14]:
data3['thall'].unique()

array([1, 2, 3, 0])

In [25]:
data['caa'].unique()

array([0, 2, 1, 3, 4])

In [26]:
var=777

In [27]:
data['caa']=data['caa'].replace(4,var)

In [28]:
data['caa'].unique()

array([  0,   2,   1,   3, 777])

In [15]:
# install jupyterthemes
pip install jupyterthemes

# upgrade to latest version
pip install --upgrade jupyterthemes

SyntaxError: invalid syntax (<ipython-input-15-d709079d8fda>, line 2)

In [16]:
!jt -t [chesterish]

zsh:1: no matches found: [chesterish]


In [ ]:
!jt -t [theme name]